# use Ubuntu and require sudo for pylint3
dist: trusty
sudo: required

# use the Python 3.5 language
language: python
python:
  - "3.5"

# cache to improve build speed
cache:
  directories:
    - $HOME/.pip-cache/

# install mdl for checking Markdown
before_install:
  - gem install mdl

# command to install dependencies
install:
  - pip install --upgrade pip
  - pip3 install --upgrade pip
  - pip install -r requirements.txt --cache-dir $HOME/.pip-cache
  - pip3 install pylint
  # - sudo apt install pylint3

# set GATORGRADER_HOME environment variable
before_script:
  - export GATORGRADER_HOME="/home/travis/build/gkapfham/gatorgrader"

# perform testing:
# --> run the internal test suite with pytest
# --> perform linting with
#     --> Python: pylint3
#     --> Markdown: mdl
script:
  - pytest tests
  - pylint3 gatorgrader.py
  - mdl README.md
